const sample = `PHYS-002C [001] | MWF 9:00am–9:50am | T 2:00pm–2:50pm | Tzer Han Tan | GH 242 / PODEM 1A22 | 2026-12-09 | 8:00am–10:59am | GH 242`;
const days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const dayMap = {M:0,T:1,W:2,R:3,F:4,S:5,U:6};
let classes = [], activeView = 'normal';
const input = document.querySelector('#schedule-input');

function parseTime(value) { const match=value.trim().match(/(\d{1,2}):(\d{2})\s*(am|pm)/i); if(!match)return null; let hour=+match[1]%12; if(match[3].toLowerCase()==='pm')hour+=12; return hour*60 + +match[2]; }
function formatTime(minutes) { if(minutes===null)return 'Time not listed'; const hour=Math.floor(minutes/60),minute=minutes%60; return `${hour%12||12}:${String(minute).padStart(2,'0')}${hour>=12?'pm':'am'}`; }
function parseMeeting(value) { const cleaned=value.trim().replace(/^\(([^)]+)\)/,'$1').replace(/–/g,'-'); const match=cleaned.match(/^([MTWRFSU]+)\s+(.+)$/i); if(!match)return null; const range=match[2].split(/\s*-\s*/),start=parseTime(range[0]||''),end=parseTime(range[1]||''); if(range.length!==2||start===null||end===null)return null; return {days:[...match[1].toUpperCase()].map(day=>dayMap[day]).filter(day=>day!==undefined),start,end}; }
function parseSchedule() {
  const parsed=[],errors=[];
  input.value.split(/\r?\n/).forEach((line,index)=>{
    if(!line.trim())return;
    const fields=line.split('|').map(value=>value.trim());
    const lecture=parseMeeting(fields[1]||''), discussion=parseMeeting(fields[2]||'');
    if(fields.length!==8||!lecture||!discussion){errors.push(index+1);return;}
    const rooms=(fields[4]||'').split('/').map(room=>room.trim());
    const finalRange=(fields[6]||'').replace(/–/g,'-').split(/\s*-\s*/);
    parsed.push({
      id:`${fields[0]}-${index}-${Date.now()}`,
      code:fields[0], courseCode:fields[0].replace(/\s*\[[^\]]+\]\s*$/,'').trim(), sectionCode:(fields[0].match(/\[([^\]]+)\]\s*$/)||[])[1]||'',
      meetings:[{...lecture,label:'Lecture',room:rooms[0]||'Room not listed'},{...discussion,label:'Discussion',room:rooms[1]||rooms[0]||'Room not listed'}],
      teacher:fields[3]||'Teacher not listed', finalDate:fields[5]||'', finalStart:parseTime(finalRange[0]||''), finalEnd:parseTime(finalRange[1]||''), finalRoom:fields[7]||'Room not listed', enrolled:false
    });
  });
  classes=parsed; document.querySelector('#import-message').textContent=errors.length?`Loaded ${parsed.length} section(s). Check line ${errors.join(', ')}: use all 8 columns in the shown order.`:`Loaded ${parsed.length} section(s). Choose the sections you want.`; render();
}
function renderCourseList() {
  const list=document.querySelector('#course-list'),groups=Object.groupBy(classes,c=>c.courseCode); list.innerHTML='';
  if(!classes.length){list.innerHTML='<div class="empty-state">Your formatted classes will appear here.</div>';return;}
  Object.entries(groups).forEach(([code,items])=>{const el=document.querySelector('#course-template').content.firstElementChild.cloneNode(true);el.querySelector('.course-code').textContent=code;el.querySelector('.section-total').textContent=`${items.length} section${items.length===1?'':'s'}`;el.querySelector('.course-toggle').onclick=()=>{el.classList.toggle('collapsed');el.querySelector('.course-toggle').setAttribute('aria-expanded',!el.classList.contains('collapsed'));};
    const container=el.querySelector('.sections');items.forEach(c=>{const card=document.createElement('div');card.className=`section-card ${c.enrolled?'enrolled':''}`;const meetingText=c.meetings.map(m=>`<strong>${m.label}:</strong> ${m.days.map(day=>days[day].slice(0,3)).join('')} ${formatTime(m.start)}–${formatTime(m.end)}<br>${m.room}`).join('<br>');card.innerHTML=`<div class="section-time">${c.sectionCode?`Section ${c.sectionCode} · `:''}${c.teacher}</div><div class="section-info">${meetingText}<br><strong>Final:</strong> ${c.finalDate} · ${formatTime(c.finalStart)}–${formatTime(c.finalEnd)}<br>${c.finalRoom}</div><button class="enroll-button ${c.enrolled?'enrolled':''}">${c.enrolled?'Unenroll':'Enroll'}</button>`;card.querySelector('button').onclick=()=>{c.enrolled=!c.enrolled;render();};container.append(card);});list.append(el);});
  document.querySelector('#course-count').textContent=`${Object.keys(groups).length} course${Object.keys(groups).length===1?'':'s'}`;
}
function getFinalDates() { const finals=classes.filter(c=>c.enrolled&&c.finalDate).map(c=>new Date(`${c.finalDate}T12:00:00`));const seed=finals.length?new Date(Math.min(...finals)):new Date();const start=new Date(seed);start.setDate(seed.getDate()-((seed.getDay()+1)%7));return Array.from({length:8},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return date;}); }
function renderCalendar() { const finalDates=activeView==='finals'?getFinalDates():null,calendar=document.querySelector('#calendar'),calendarDays=finalDates||days;calendar.style.gridTemplateColumns=`52px repeat(${calendarDays.length}, minmax(105px,1fr))`;calendar.innerHTML='<div class="corner"></div>';calendarDays.forEach((day,index)=>{const h=document.createElement('div');h.className='day-name';h.style.gridColumn=index+2;h.innerHTML=finalDates?`${days[(day.getDay()+6)%7].slice(0,3)}<br><span class="date-label">${day.getMonth()+1}/${day.getDate()}/${day.getFullYear()}</span>`:day;calendar.append(h);});const timeCol=document.createElement('div');timeCol.className='time-column';for(let hour=8;hour<=20;hour++){const t=document.createElement('span');t.className='time-label';t.style.top=`${(hour-8)*60}px`;t.textContent=formatTime(hour*60).replace(':00','');timeCol.append(t);}calendar.append(timeCol);const area=document.createElement('div');area.className='grid-area';area.style.gridColumn=`2 / ${calendarDays.length+2}`;for(let i=0;i<calendarDays.length;i++){const col=document.createElement('div');col.className='day-column';col.style.left=`${i*100/calendarDays.length}%`;col.style.width=`${100/calendarDays.length}%`;area.append(col);}classes.filter(c=>c.enrolled).forEach(c=>{if(activeView==='normal')c.meetings.forEach(m=>m.days.forEach(day=>addEvent(area,c,day,m.start,m.end,false,m,7)));else if(c.finalDate&&c.finalStart!==null&&c.finalEnd!==null){const exam=new Date(`${c.finalDate}T12:00:00`),day=finalDates.findIndex(date=>date.toDateString()===exam.toDateString());if(day>=0)addEvent(area,c,day,c.finalStart,c.finalEnd,true,null,finalDates.length);}});calendar.append(area);const enrolled=classes.filter(c=>c.enrolled).length;document.querySelector('#enrollment-count').textContent=`${enrolled} enrolled`;document.querySelector('#calendar-title').textContent=activeView==='normal'?'Normal week':'Finals week';document.querySelector('#calendar-caption').textContent=activeView==='normal'?'Enrolled lectures and discussions are shown in blue.':'Your enrolled final exams are shown in gold.'; }
function addEvent(area,c,day,start,end,final,meeting,columnCount) { const visibleStart=Math.max(start,480),visibleEnd=Math.min(end,1200);if(visibleEnd<=visibleStart)return;const event=document.createElement('article');event.className=`class-event${final?' final':''}`;event.style.left=`calc(${day*100/columnCount}% + 3px)`;event.style.width=`calc(${100/columnCount}% - 6px)`;event.style.top=`${visibleStart-480}px`;event.style.height=`${Math.max(42,visibleEnd-visibleStart-3)}px`;const room=final?c.finalRoom:meeting.room,tag=final?'FINAL':meeting.label.toUpperCase();event.innerHTML=`<span class="event-tag">${tag}</span><div class="event-time">${formatTime(start)} - ${formatTime(end)}</div><div class="event-code">${c.code}</div><div class="event-detail">${c.teacher}<br>${room}</div>`;area.append(event); }
function render(){renderCourseList();renderCalendar();}
document.querySelector('#parse-button').onclick=parseSchedule;document.querySelector('#load-sample').onclick=()=>{input.value=sample;parseSchedule();};document.querySelectorAll('.view-button').forEach(button=>button.onclick=()=>{activeView=button.dataset.view;document.querySelectorAll('.view-button').forEach(other=>other.classList.toggle('active',other===button));renderCalendar();});input.value=sample;parseSchedule();
